[Lab 1] Add website markup
Neoxenr/effective-web-course pull request #1
Opened 2022-10-31 10:20 UTC by Neoxenr

Долгушин Иван.

Имеются следующие вопросы:

1) Как можно сделать эту сетку отзывчивой не прибегая к костылям? У меня это не особо получилось, пришлось добавлять очень много не очень хорошего кода. 
![image](https://user-images.githubusercontent.com/71054842/198985296-84d92479-2259-4820-b19a-bad717430b45.png)

2) Как добавить синие линии снизу блока, если z-index с box-shadow не работает? Искал на стеке информацию об этом. Там советуют использовать значение inset для box-shadow, но оно никак не решает проблему.  
![image](https://user-images.githubusercontent.com/71054842/198985512-7bc20042-c2d3-472c-9c59-a42c3fec205a.png)

3) Есть ли какие-то методы для того, чтобы сделать шрифт отзывчивым, помимо em и rem?

4) Как правильно группировать стили?

Спасибо.

2022-11-02 05:48 UTC, konstantinzelinsky commented
Привет!
1) Можно задавать максимальную ширину для контейнера. Использовать `fr` для задания размеров элементов и свойство `grid-template-areas`. Изменять их в media запросах.
2) Можно использовать псевдо элемент, в контент закинуть картинку, позиционирование абсолютное + z-index
3) Можно просто использовать медиа запросы. Можно использовать vw / vh (то есть относительно размеров окна браузера) Это не критично в рамках данной лабораторной
4) Логически по блокам. например - header, footer, cards-section и т.д

Переименуй, пожалуйста, PR для получения доп баллов за гит.
Например, так - [Lab 1] Add website markup
Не совсем понятно зачем нужны скобки в названиях коммитов. Кажется, они лишние.

Также не понятно зачем везде в стилях отступ в начале описания.

2022-11-02 05:49 UTC, konstantinzelinsky requested changes
Переименовать PR и добавить синие линии под блоком

2022-11-04 06:47 UTC, Neoxenr commented
Исправил ошибки.

2022-11-04 09:13 UTC, konstantinzelinsky commented
Принял. 14 баллов

2022-11-04 09:13 UTC, konstantinzelinsky approved these changes

2022-11-04 09:13 UTC, merged